name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Setup Yarn
      run: npm install -g yarn
    - name: Install Deps
      run: yarn install
    - name: Run coverage
      run: yarn cross-env CI=1 yarn run coverage
